Undefined reference to `solve_core' (#430)
* Fixing missing dependency in the makefile target
* enginemch.o is needed before creation of shared/static library libcorenrnmech created